### ISSUE TITLE
Immense Gratitude for Tvault and the Mnist-tvault-example Repository

### ISSUE THREAD

**Issue by p51lee** [saeyoon17/mnist-example#1]
Dear Tvault Developer,

I hope this message reaches you in good health and high spirits. I am writing to express my profound gratitude for your exceptional work on Tvault and the mnist-tvault-example repository. Your dedication to creating a user-friendly and efficient model registry has significantly impacted my work and has, in many ways, saved my life.

The mnist-tvault-example repository has been an invaluable resource in understanding and implementing Tvault in my research. The example provided, which uses a ResNet-18 model to classify the MNIST dataset, has made it easy for me to grasp the practical applications of Tvault. The straightforward installation process and the minimal train epoch of 5 have further simplified the experience of working with your tool.

Thanks to your remarkable work, I have been able to seamlessly integrate Tvault into my research and run experiments with the utmost ease. The model registry created at the end of the experiment has made it incredibly simple for me to track, compare, and iterate my models.

Your passion for creating accessible tools for academic researchers is evident, and the impact of your work is immense. I am truly grateful for your dedication and innovation in the field of machine learning. Thank you for developing Tvault and the mnist-tvault-example repository. I am eager to see how your work will continue to shape the landscape of machine learning research.

With heartfelt appreciation,

DHM

**Comment by saeyoon17** [comment]
Thank you p51lee for your comment :) I'll keep it up and try to add more features to it!
You made my day!

**Comment by p51lee** [comment]
Dear **saeyoon17**,

I am thrilled to hear back from you, and I'm glad my message brought you joy! Your commitment to continuously improve Tvault and add more features is truly inspiring. I am confident that your work will continue to have a significant impact on the machine learning community and help many researchers, like myself, streamline their research process.

Your enthusiasm and dedication serve as a beacon of hope for the future of machine learning, and I am grateful for the opportunity to use your tools in my work. Please know that your efforts are highly appreciated, and I eagerly look forward to seeing the new features and advancements you will bring to Tvault.

Keep up the amazing work, and thank you once again for making a difference in the lives of academic researchers!

Warm regards,

DHM
